name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2.3.1
      - name: Install dependencies (if needed)
        run: |
          apt-get update
          apt-get install -y build-essential
      - name: Make version
        run: |
          make --version
      - name: Build and Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd /root/hackaton/go-split-api/
            git fetch
            git pull
            make build
            systemctl restart split-api-daemon.service

permissions:
  contents: write